### 1. Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np
#numpy array can be directly added with operator
def add(mat1,mat2):
    if(mat1.shape == mat2.shape):
        mat3 = np.zeros(mat1.shape)
        for i in range(mat1.shape[0]):
            for j in range(mat2.shape[1]):
                mat3[i][j] = mat1[i][j] + mat2[i][j]
        return mat3
    else:
        return "not possible"

m,n = map(int,input("enter the shape of the matrix").split(" "))
mat1,mat2 = np.random.rand(m,n),np.random.rand(m,n)
print(mat1,mat2,sep = "\n")
print(f"addition is = {add(mat1,mat2)}")

enter the shape of the matrix3 3
[[0.96786124 0.04042869 0.51118206]
 [0.48171866 0.23187452 0.38685536]
 [0.20800612 0.37448262 0.01714592]]
[[0.56000526 0.63013742 0.72626968]
 [0.0231014  0.13327384 0.56806885]
 [0.01893149 0.47626197 0.1868303 ]]
addition is = [[1.5278665  0.67056611 1.23745174]
 [0.50482006 0.36514836 0.95492421]
 [0.2269376  0.85074459 0.20397623]]


### 2. Write a Python Program to Multiply Two Matrices?

In [19]:

def multiply(mat1,mat2):
    m1,n1 = mat1.shape
    m2,n2 = mat2.shape
    if n1==m2:
        mat3 = np.zeros((m1,n2))
        for i in range(m1):
            for j in range(n2):
                for k in range(n1):
                    mat3[i][j] += mat1[i][k] * mat2[k][j]
        return mat3
    else:
        return "not possible"

m,n = map(int,input("enter the shape of the matrix").split(" "))
mat1,mat2 = np.random.rand(m,n),np.random.rand(m,n)
print(mat1,mat2,sep = "\n")
print()
print(f"Multiplication is = {multiply(mat1,mat2)}")
print()
print(np.matmul(mat1,mat2))

enter the shape of the matrix3 3
[[0.59060353 0.2513306  0.1957517 ]
 [0.49457011 0.71578526 0.57144599]
 [0.28700668 0.36125877 0.6615934 ]]
[[0.99666309 0.50877267 0.08567724]
 [0.66709156 0.79674237 0.41417108]
 [0.20136522 0.6742999  0.72486126]]

Multiplication is = [[0.79571086 0.63272403 0.29658797]
 [1.08548343 1.20724617 0.75305001]
 [0.66026355 0.87996369 0.6537763 ]]

[[0.79571086 0.63272403 0.29658797]
 [1.08548343 1.20724617 0.75305001]
 [0.66026355 0.87996369 0.6537763 ]]


In [18]:
m1,n1 = mat1.shape
m2,n2 = mat2.shape
if n1==m2:
    mat3 = np.zeros((m1,n2))
    for i in range(m1):
        for j in range(n2):
            print(f"mat3[{i}][{j}] =",end = "")
            for k in range(n1):
                print(f" mat1[{i}][{k}]*mat2[{k}][{j}]",end ="+")
            print()
        print()

mat3[0][0] = mat1[0][0]*mat2[0][0]+ mat1[0][1]*mat2[1][0]+ mat1[0][2]*mat2[2][0]+
mat3[0][1] = mat1[0][0]*mat2[0][1]+ mat1[0][1]*mat2[1][1]+ mat1[0][2]*mat2[2][1]+
mat3[0][2] = mat1[0][0]*mat2[0][2]+ mat1[0][1]*mat2[1][2]+ mat1[0][2]*mat2[2][2]+

mat3[1][0] = mat1[1][0]*mat2[0][0]+ mat1[1][1]*mat2[1][0]+ mat1[1][2]*mat2[2][0]+
mat3[1][1] = mat1[1][0]*mat2[0][1]+ mat1[1][1]*mat2[1][1]+ mat1[1][2]*mat2[2][1]+
mat3[1][2] = mat1[1][0]*mat2[0][2]+ mat1[1][1]*mat2[1][2]+ mat1[1][2]*mat2[2][2]+

mat3[2][0] = mat1[2][0]*mat2[0][0]+ mat1[2][1]*mat2[1][0]+ mat1[2][2]*mat2[2][0]+
mat3[2][1] = mat1[2][0]*mat2[0][1]+ mat1[2][1]*mat2[1][1]+ mat1[2][2]*mat2[2][1]+
mat3[2][2] = mat1[2][0]*mat2[0][2]+ mat1[2][1]*mat2[1][2]+ mat1[2][2]*mat2[2][2]+



### 3. Write a Python Program to Transpose a Matrix?

In [41]:
#rows become columns and vice versa
#this function only works for square matrixb
# def transpose(mat):
#     m,n = mat.shape
#     mat1 = np.zeros((n,m))
#     for i in range(m):
#         for j in range(n):
#             mat1[i][j] = mat[j][i]
            
#     return mat1

def transpose(mat):
    m,n = mat.shape
    mat1 = np.zeros((n,m))
    for i in range(n):
        mat1[i] = mat[:,i]
    return mat1
    

m,n = map(int,input("enter the shape of the matrix").split(" "))
mat1 = np.random.rand(m,n)
print(mat1,sep = "\n")
print(f"transpose is = {transpose(mat1)}")
print()
print(f"Inbuilt function is {mat1.T}")

enter the shape of the matrix3 2
[[0.13193015 0.48342758]
 [0.73910816 0.58994171]
 [0.36489054 0.80130405]]
transpose is = [[0.13193015 0.73910816 0.36489054]
 [0.48342758 0.58994171 0.80130405]]

Inbuilt function is [[0.13193015 0.73910816 0.36489054]
 [0.48342758 0.58994171 0.80130405]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [42]:
def sortin(s):
    return sorted(s)

s = input("enter any word : ")
print(sortin(s))

enter any word : harsha
['a', 'a', 'h', 'h', 'r', 's']


### 5. Write a Python Program to Remove Punctuation From a String?

In [49]:
punctuation = ['!','.',',','?',';',':','/','(',')','-','"','@']
s = input("enter any word with puctuation in it : ")
for i in punctuation:
    s = s.replace(i,"")
print(s)


enter any word with puctuation in it : harsha999ar@gmail.com
harsha999argmailcom
